import { useEffect } from 'react';

import type { NextPage } from 'next';

import Head from 'next/head';
import { useRouter } from 'next/router';

import { decodeUrl } from '../lib/urlExtender';

const Home: NextPage = () => {
  const { asPath } = useRouter();

  useEffect(() => {
    const url = decodeUrl(asPath);
    window.location.href = String(url);
  }, [asPath]);

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
