import { ChangeEventHandler, FormEventHandler, useState } from 'react';

import type { NextPage } from 'next';

import Head from 'next/head';

import { encodeUrl } from '../lib/urlExtender';
import { urlValidator } from '../lib/urlValidator';

const Home: NextPage = () => {
  const [inputValue, setInputValue] = useState('');
  const [encodedUrl, setEncodedUrl] = useState('');

  const handleChange: ChangeEventHandler<HTMLInputElement> = (event) => {
    setInputValue(event.target.value);
  };

  const handleSubmit: FormEventHandler<HTMLFormElement> = (event) => {
    event.preventDefault();
    if (urlValidator(inputValue)) {
      setEncodedUrl(`${window.location.origin}/${encodeUrl(inputValue)}`);
    } else {
      alert('Invalid URL.');
    }
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(encodedUrl);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={handleSubmit}>
        <input onChange={handleChange} />
        <button type="submit" className="font-extrabold">
          EXTEND
        </button>
        <button onClick={handleCopy} type="button" className="font-extrabold">
          COPY
        </button>
      </form>
      <div className="my-2 flex w-full flex-col break-all rounded border p-2">
        {encodedUrl}
      </div>
    </>
  );
};

export default Home;
